site_name: 'Quix Docs'
site_description: 'Quix Developer Documentation. Includes documentation (tutorials, reference guides, how-tos, concepts) for Quix Platform, Quix Streams client library, and REST and websocket APIs.'
site_author: 'Quix.io'
site_url: 'https://quix.io/docs'

copyright: >
  Copyright &copy; 2020 - 2023 Quix Analytics, Ltd. –
  <a href="#__consent">Change cookie settings</a>

docs_dir: docs/
repo_name: quixio/quix-docs
repo_url: https://github.com/quixio/quix-docs
edit_uri: tree/dev/docs

nav:
  - 'Get started':
    - 'Welcome': 'get-started/welcome.md'
    - 'Quickstart': 'get-started/quickstart.md'
    - 'Quix Tour': 
      - 'get-started/quixtour/index.md'
      - '1. Ingest': 'get-started/quixtour/ingest-push.md'
      - '2. Process': 'get-started/quixtour/process-threshold.md'
      - '3. Serve': 'get-started/quixtour/serve-sms.md'
    - 'What is Quix?': 'get-started/what-is-quix.md'
    - 'Glossary': 'get-started/glossary.md'
    - 'Contribute': 'get-started/contribute.md'
  - 'Create':
      - 'create/index.md'
      - 'Create a project': 'create/create-project.md'
      - 'Create an environment': 'create/create-environment.md'
      - 'Protected environments': 'create/protected-environment.md'
      - 'Syncing an environment': 'create/syncing-environment.md'
      - 'Project structure': 'create/project-structure.md'
  - 'Develop':
      - 'develop/index.md'
      - 'Create an application': 'develop/create-application.md'
      - 'Code Samples': 'develop/code-samples.md'
      - 'Integrate your data':
        - 'develop/integrate-data/index.md'
        - 'Prebuilt connectors': 'develop/integrate-data/prebuilt-connector.md'
        - 'Read CSV file': 'develop/integrate-data/read-csv.md'
        - 'Polling': 'develop/integrate-data/polling.md'
        - 'Inbound webhooks': 'develop/integrate-data/inbound-webhooks.md'
        - 'Streaming API - HTTP': 'develop/integrate-data/streaming-http.md'
        - 'Streaming API - SignalR': 'develop/integrate-data/streaming-signalr.md'
        - 'Quix Streams': 'develop/integrate-data/quix-streams.md'
        - 'Web app': 'develop/integrate-data/web-app.md'
        - 'Export to Jupyter notebooks': 'develop/integrate-data/jupyter-nb.md'
      - 'Process your data':
        - 'Types of processing': 'develop/types-of-processing.md'
        - 'Types of transform': 'develop/types-of-transform.md'
      - 'Generating events': 'develop/timeseries-events.md'
  - 'Deploy':
    - 'deploy/index.md'
    - 'Environment variables': 'deploy/environment-variables.md'
    - 'Secrets management': 'deploy/secrets-management.md'
    - 'YAML variables': 'deploy/yaml-variables.md'
    - 'State management': 'deploy/state-management.md'  
    - 'Deploy public services': 'deploy/deploy-public-page.md'
  - 'Manage':
    - 'manage/index.md'
    - 'Troubleshooting': 'manage/troubleshooting.md'
    - 'Security': 'manage/security.md'
    - 'MLOps': 'manage/MLOps.md'
    - 'Using replay service': 'manage/replay.md'
    - 'Testing using Quix data store': 'manage/testing-data-store.md'
  - 'Tutorials':
    - 'tutorials/index.md'
    - 'Computer vision': 
      - tutorials/computer-vision/index.md
      - '1. Get the project': tutorials/computer-vision/get-project.md
      - '2. TfL camera feed': tutorials/computer-vision/tfl-camera-feed.md
      - '3. Frame grabber': tutorials/computer-vision/tfl-frame-grabber.md
      - '4. Object detection': tutorials/computer-vision/object-detection.md
      - '5. Web UI': tutorials/computer-vision/web-ui.md
      - '6. Other services': tutorials/computer-vision/other-services.md
      - '7. Add service': tutorials/computer-vision/add-service.md
      - '8. Summary': tutorials/computer-vision/summary.md        
    - 'Chat sentiment analysis': 
      - tutorials/sentiment-analysis/index.md
      - '1. Get the project': tutorials/sentiment-analysis/get-project.md
      - '2. Try the UI': 'tutorials/sentiment-analysis/try-the-ui.md'
      - '3. UI service': 'tutorials/sentiment-analysis/ui-service.md'
      - '4. Sentiment analysis service': 'tutorials/sentiment-analysis/sentiment-analysis-service.md'
      - '5. Twitch service': 'tutorials/sentiment-analysis/twitch-service.md'
      - '6. Customize the UI': 'tutorials/sentiment-analysis/customize-the-ui.md'
      - '7. Summary': 'tutorials/sentiment-analysis/summary.md'
    - 'Real-time ML predictions':
      - 'tutorials/data-science/index.md'
      - '1. Bicycle data': 'tutorials/data-science/1-bikedata.md'
      - '2. Weather data': 'tutorials/data-science/2-weatherdata.md'
      - '3. Data views': 'tutorials/data-science/3-data.md'
      - '4. Get training data': 'tutorials/data-science/4-train.md'
      - '5. Run the model': 'tutorials/data-science/5-run.md'
      - '6. Conclusion': 'tutorials/data-science/6-conclusion.md'
    - 'Real-time ML pipelines':
      - tutorials/train-and-deploy-ml/index.md
      - 'Create your data': 'tutorials/train-and-deploy-ml/create-data.md'
      - 'Import data into Jupyter': 'tutorials/train-and-deploy-ml/import-data.md'
      - 'Train your ML model': 'tutorials/train-and-deploy-ml/train-ml.md'
      - 'Deploy your ML model': 'tutorials/train-and-deploy-ml/deploy-ml.md'
      - 'Conclusion': 'tutorials/train-and-deploy-ml/conclusion.md'
    - 'Real-time event detection':
      - 'tutorials/event-detection/index.md'
      - '1. Data acquisition': 'tutorials/event-detection/data-acquisition.md'
      - '2. Event detection': 'tutorials/event-detection/crash-detection.md'
      - '3. Demo UI': 'tutorials/event-detection/crash-detection-ui.md'
      - '4. Conclusion': 'tutorials/event-detection/conclusion.md'
    - 'RSS Processing': 'tutorials/rss-tutorial/rss-processing-pipeline.md'
    - 'Currency Alerting': 'tutorials/currency-alerting/currency-alerting.md'
    - 'Data Stream Processing': 'tutorials/data-stream-processing/data-stream-processing.md'
    - 'Slack Alerting': 'tutorials/slack-alerting/slack-alerting.md'
    - 'MATLAB and Simulink': 'tutorials/matlab/matlab-and-simulink.md'
  - 'Reference':
    - 'Connectors': 
      - 'connectors/index.md'
#ConnectorsGetInsertedHere
    - 'APIs':
      - 'APIs overview': 'apis/index.md'
      - 'Streaming Writer API': 
        - 'apis/streaming-writer-api/index.md'
        - 'Setup': 'apis/streaming-writer-api/setup.md'
        - 'HTTP requests': 'apis/streaming-writer-api/http-requests.md'
        - 'Create a new Stream': 'apis/streaming-writer-api/create-stream.md'
        - 'Add Stream metadata': 'apis/streaming-writer-api/stream-metadata.md'
        - 'Send Parameter data': 'apis/streaming-writer-api/send-data.md'
        - 'Send an Event': 'apis/streaming-writer-api/send-event.md'
      - 'Streaming Reader API': 
        - 'apis/streaming-reader-api/index.md'
        - 'Setup': 'apis/streaming-reader-api/setup.md'
        - 'HTTP requests': 'apis/streaming-reader-api/http-requests.md'
        - 'Reading data': 'apis/streaming-reader-api/reading-data.md'
        - 'Subscription and events': 'apis/streaming-reader-api/subscriptions.md'
      - 'Query API': 
        - 'apis/query-api/index.md'
        - 'Setup': 'apis/query-api/setup.md'
        - 'HTTP requests': 'apis/query-api/http-requests.md'
        - 'Paged streams': 'apis/query-api/streams-paged.md'
        - 'Filtered streams': 'apis/query-api/streams-filtered.md'
        - 'Streams with models': 'apis/query-api/streams-models.md'
        - 'Raw data': 'apis/query-api/raw-data.md'
        - 'Aggregate data by time': 'apis/query-api/aggregate-time.md'
        - 'Aggregate data by tags': 'apis/query-api/aggregate-tags.md'
        - 'Tag filtering': 'apis/query-api/filter-tags.md'
      - 'Portal API': 
        - 'apis/portal-api/index.md'
        - 'Setup': 'apis/portal-api/setup.md'
        - 'HTTP requests': 'apis/portal-api/http-requests.md'
    - 'Client Library': '!import https://github.com/quixio/quix-streams?branch=main'

plugins:
  - multirepo:
      cleanup: true
  - search:
      separator: '[\s\-\.]' 
  - social:
      cards_layout_dir: layouts
      cards_layout: quix
  - glightbox
  - redirects:
      redirect_maps:
        'index.md': 'get-started/welcome.md'
        'platform/tutorials/computer-vision/index.md': 'tutorials/computer-vision/index.md'
        'platform/tutorials/currency-alerting/currency-alerting.md': 'tutorials/currency-alerting/currency-alerting.md'
        'platform/tutorials/data-science/index.md': 'tutorials/data-science/index.md'
        'platform/tutorials/data-stream-processing/data-stream-processing.md': 'tutorials/data-stream-processing/data-stream-processing.md'
        'platform/tutorials/event-detection/index.md': 'tutorials/event-detection/index.md'
        'platform/tutorials/matlab/matlab-and-simulink.md': 'tutorials/matlab/matlab-and-simulink.md'
        'platform/tutorials/nocode-sentiment/nocode-sentiment-analysis.md': 'tutorials/sentiment-analysis/index.md'
        'platform/tutorials/rss-tutorial/rss-processing-pipeline.md': 'tutorials/rss-tutorial/rss-processing-pipeline.md'
        'platform/tutorials/sentiment-analysis/index.md': 'tutorials/sentiment-analysis/index.md'
        'platform/tutorials/slack-alerting/slack-alerting.md': 'tutorials/slack-alerting/slack-alerting.md'
        'platform/tutorials/train-and-deploy-ml/index.md': 'tutorials/train-and-deploy-ml/index.md'
        
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - content.code.copy
  # TODO
  #custom_dir: 'theme'
  favicon: 'assets/favicon.ico'
  
  palette: 
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  features:
  - navigation.instant     # Instant loading pages.
#  - navigation.sections    # Render top sections as groups.
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  - navigation.indexes     # Documents can be directly attached to sections
  - search.highlight       # Search will highlight the searched word(s) on the page.*
  - search.share           # Adds an option to share a search query link.*
  - search.suggest         # Search will suggest the likeliest completion for a word.*
  - content.tabs.link
  - content.code.annotate  # code annotations
  - content.action.view    # view page source
  - content.code.copy
  
  icon:
    logo: 'material/library'
    repo: 'material/library'
  

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/quix.js
  - javascripts/feedback.js
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/quixio/quix-docs'
    - icon: 'fontawesome/brands/slack'
      link: 'https://quix.io/community'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/quix_io'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCrijXvbQg67m9-le28c7rPA'
  analytics:
    provider: google-tag-manager
    property: GTM-55L66N3
  posthog:
    host: https://eu.posthog.com
    key: phc_UyQcafs2J7OUQEwJrmejeb0vCIdA9i9vYz66suPshix
  hotjar:
    id: 2437577
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      posthog: Posthog
  
  #alternate:
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
