name: Build and Commit to Subdir

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
env:
  #SITE_DIR: ${{ github.ref_name }}
  SITE_DIR: subsite
# on: push
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'dev'
  #  paths:
  #    - '**.md'
  #pull_request:
  #  types: [opened, reopened]
    # Only trigger automatically when certain tags are added
    #tags:
    #- v1.**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-html:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
    # Runs a single command using the runners shell
      
    - name: Checkout Dev
      uses: actions/checkout@v3
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: python -m pip install --upgrade pip setuptools wheel
    
    # Needed when using more than one repo
    # add 'monorepo' to mkdocs.yml file under plugins
    - run: pip install mkdocs-monorepo-plugin
    
    # Commenting out material insiders install until get proper token back.
    - run: pip install git+https://${{ env.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: pip install mkdocs
    #- run: pip install mkdocs-material
    
    - name: Build the Docs
      run: mkdocs build --no-directory-urls
      
    #- run: mkdir branch  
    #- name: Copy the built docs to a subdir
    # run: cp -R ./site ./branch/${{ env.SITE_DIR }}
      
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az login --service-principal -u e4c6c5fb-9968-4aac-bb7b-09adf7ae9ee7 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            az storage container create --name ${{ env.SITE_DIR }} --public-access container --account-name quixdocs
            az storage blob upload-batch --account-name quixdocs --auth-mode key -d '${{ env.SITE_DIR }}' -s site

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
          
    #- name: Authenticate on GCS
    #  uses: google-github-actions/auth@v0
    #  with:
    #   service_account: '${{ secrets.GCP_SA_EMAIL }}'
    #   credentials_json: '${{ secrets.GCP_SA_KEY }}'

    #- name: Set up Cloud SDK
    #  uses: google-github-actions/setup-gcloud@v0 
      
    #- run: gsutil -m rsync -d -c -r branch gs://quix-docs-test
      


