# Adding Workflow to Branch
name: Sync with Quix Docs Dev
on:
  workflow_dispatch:   # run manually
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       ref: main
       fetch-depth: 10
    - run: echo "This job needs to be run from the workflow branch rather than main" 
